name: Feature request
description: Propose a feature or enhancement to help Cameradar improve
labels:
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Please make sure your request is not already proposed in another issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give a clear and concise description of the feature request.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: Additional info you want to provide.
    validations:
      required: false
